# Generated by Django 4.2.3 on 2023-11-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'USER PROFILE', 'verbose_name_plural': 'USER PROFILES'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='channel',
        ),
    ]
